// dummy-schedule.ts
export const scheduleBlocksLine1 = [
    {
        id: "line-1",
        machine: "MC 1",
        shift: "08:00 - 16:00",
        rows: [
            {
                code: "4345",
                qty: 450,
                stock: 120,
                totalQty: 750,
                startTime: "08:00",
                endTime: "14:00",
                start: 8,
                end: 14,
                remark: "",
                phases: [
                    { type: "building", start: 8.25, end: 10 },
                    { type: "buffer", start: 10, end: 10.20 },
                    { type: "curing", start: 10.20, end: 13.25 },
                    { type: "idle", start: 13.25, end: 14.25 },
                ],
            },
            {
                code: "4399",
                qty: 300,
                stock: 50,
                totalQty: 750,
                startTime: "14:00",
                endTime: "19:00",
                start: 14,
                end: 19,
                remark: "URGENT",
                phases: [
                    { type: "curing", start: 14, end: 18 },
                    { type: "buffer", start: 18, end: 19 },
                ],
            },
            {
                code: "4346",
                qty: 750,
                stock: 200,
                totalQty: 1500,
                startTime: "09:00",
                endTime: "18:00",
                start: 9,
                end: 18,
                remark: "",
                phases: [
                    { type: "building", start: 9, end: 11 },
                    { type: "curing", start: 11, end: 14 },
                    { type: "idle", start: 14, end: 15 },
                    { type: "curing", start: 15, end: 17 },
                    { type: "buffer", start: 17, end: 18 },
                ],
            },
        ],
    },

    {
        id: "line-2",
        machine: "MC 2",
        shift: "08:00 - 16:00",
        rows: [
            {
                code: "4345",
                qty: 350,
                stock: 80,
                totalQty: 1000,
                startTime: "08:00",
                endTime: "12:00",
                start: 8,
                end: 12,
                remark: "",
                phases: [
                    { type: "building", start: 8, end: 10 },
                    { type: "curing", start: 10, end: 12 },
                ],
            },
            {
                code: "4617",
                qty: 400,
                stock: 150,
                totalQty: 1000,
                startTime: "12:00",
                endTime: "17:00",
                start: 12,
                end: 17,
                remark: "",
                phases: [
                    { type: "idle", start: 12, end: 13 },
                    { type: "curing", start: 13, end: 16 },
                    { type: "buffer", start: 16, end: 17 },
                ],
            },
            {
                code: "4617",
                qty: 750,
                stock: 300,
                totalQty: 1500,
                startTime: "09:00",
                endTime: "19:00",
                start: 9,
                end: 19,
                remark: "",
                phases: [
                    { type: "building", start: 9, end: 11 },
                    { type: "curing", start: 11, end: 14 },
                    { type: "idle", start: 14, end: 15 },
                    { type: "curing", start: 15, end: 18 },
                    { type: "buffer", start: 18, end: 19 },
                ],
            },
        ],
    },

    {
        id: "line-3",
        machine: "MC 3",
        shift: "08:00 - 16:00",
        rows: [
            {
                code: "4392",
                qty: 750,
                stock: 40,
                totalQty: 800,
                startTime: "09:00",
                endTime: "18:00",
                start: 9,
                end: 18,
                remark: "",
                phases: [
                    { type: "building", start: 9, end: 11 },
                    { type: "curing", start: 11, end: 14 },
                    { type: "idle", start: 14, end: 15 },
                    { type: "curing", start: 15, end: 17 },
                    { type: "buffer", start: 17, end: 18 },
                ],
            },
        ],
    },

    {
        id: "line-4",
        machine: "MC 4",
        shift: "08:00 - 16:00",
        rows: [
            {
                code: "4667",
                qty: 750,
                stock: 90,
                totalQty: 1200,
                startTime: "08:00",
                endTime: "17:00",
                start: 8,
                end: 17,
                remark: "",
                phases: [
                    { type: "building", start: 8, end: 10 },
                    { type: "curing", start: 10, end: 13 },
                    { type: "idle", start: 13, end: 14 },
                    { type: "curing", start: 14, end: 16 },
                    { type: "buffer", start: 16, end: 17 },
                ],
            },
        ],
    },

    {
        id: "line-5",
        machine: "MC 5",
        shift: "08:00 - 16:00",
        rows: [
            {
                code: "4528",
                qty: 750,
                stock: 0,
                totalQty: 750,
                startTime: "09:00",
                endTime: "15:00",
                start: 9,
                end: 15,
                remark: "BESOK SHUTDOWN",
                phases: [
                    { type: "building", start: 9, end: 10.5 },
                    { type: "curing", start: 10.5, end: 13 },
                    { type: "idle", start: 13, end: 14 },
                    { type: "buffer", start: 14, end: 15 },
                ],
            },
        ],
    },
];
export const scheduleBlocksLine2 = [
    {
        id: "line-2-mc-11",
        machine: "MC 11",
        shift: "08:00 - 16:00",
        rows: [
            {
                code: "4617",
                qty: 600,
                stock: 250,
                totalQty: 1000,
                startTime: "08:00",
                endTime: "16:00",
                start: 8,
                end: 16,
                remark: "",
                phases: [
                    { type: "building", start: 8, end: 11 },
                    { type: "curing", start: 11, end: 15 },
                    { type: "idle", start: 15, end: 16 },
                ],
            },
        ],
    },
    {
        id: "line-2-mc-12",
        machine: "MC 12",
        shift: "08:00 - 16:00",
        rows: [
            {
                code: "4742",
                qty: 500,
                stock: 100,
                totalQty: 800,
                startTime: "09:00",
                endTime: "15:00",
                start: 9,
                end: 15,
                remark: "",
                phases: [
                    { type: "building", start: 9, end: 11 },
                    { type: "curing", start: 11, end: 14 },
                    { type: "buffer", start: 14, end: 15 },
                ],
            },
        ],
    },
];

export const PRODUCTION_LINES = [
    { id: "pcr-1", name: "PCR Line 1", data: scheduleBlocksLine1 },
    { id: "pcr-2", name: "PCR Line 2", data: scheduleBlocksLine2 },
];
