// dummy-schedule.ts
export const scheduleBlocksLine1 = [
    {
        id: "line-1",
        machine: "MC 1",
        shift: "All Shifts",
        rows: [
            // Shift 1 (08:00 - 16:00) - Multi Code
            {
                code: "4345",
                balanceOut: 100,
                qty: 200,
                stock: 120,
                totalQty: 750,
                startTime: "08:00",
                endTime: "12:00",
                start: 8,
                end: 12,
                remark: "Shift 1",
                rim: "16",
                cureShift: 20,
                rcStock: 15,
                cureEst: "08:15",
                buildTime: "08:30 - 10:00",
                shiftNum: 1,
                phases: [
                    { type: "building", start: 8.5, end: 10 },
                    { type: "curing", start: 10, end: 12 },
                ],
            },
            {
                code: "4392",
                balanceOut: 100,
                qty: 250,
                stock: 40,
                totalQty: 800,
                startTime: "12:00",
                endTime: "16:00",
                start: 12,
                end: 16,
                remark: "Shift 1",
                rim: "14",
                cureShift: 25,
                rcStock: 10,
                cureEst: "12:10",
                buildTime: "12:30 - 14:00",
                shiftNum: 1,
                phases: [
                    { type: "building", start: 12.5, end: 14 },
                    { type: "curing", start: 14, end: 15.5 },
                    { type: "idle", start: 15.5, end: 16 },
                ],
            },
            // Shift 2 (16:00 - 24:00)
            {
                code: "4346",
                balanceOut: 100,
                qty: 750,
                stock: 200,
                totalQty: 1500,
                startTime: "16:00",
                endTime: "24:00",
                start: 16,
                end: 24,
                remark: "Shift 2",
                rim: "16",
                cureShift: 45,
                rcStock: 20,
                cureEst: "16:20",
                buildTime: "16:30 - 19:00",
                shiftNum: 2,
                phases: [
                    { type: "building", start: 16.5, end: 19 },
                    { type: "curing", start: 19, end: 23 },
                    { type: "buffer", start: 23, end: 24 },
                ],
            },
            // Shift 3 (24:00 - 08:00) - Multi Code
            {
                code: "4399",
                balanceOut: 100,
                qty: 150,
                stock: 50,
                totalQty: 750,
                startTime: "00:00",
                endTime: "04:00",
                start: 24,
                end: 28,
                remark: "Shift 3",
                rim: "15",
                cureShift: 19,
                rcStock: 8,
                cureEst: "00:10",
                buildTime: "00:30 - 02:00",
                shiftNum: 3,
                phases: [
                    { type: "curing", start: 24.5, end: 27 },
                    { type: "idle", start: 27, end: 28 },
                ],
            },
            {
                code: "4528",
                balanceOut: 100,
                qty: 150,
                stock: 0,
                totalQty: 750,
                startTime: "04:00",
                endTime: "08:00",
                start: 28,
                end: 32,
                remark: "Shift 3",
                rim: "14",
                cureShift: 19,
                rcStock: 5,
                cureEst: "04:10",
                buildTime: "04:30 - 06:00",
                shiftNum: 3,
                phases: [
                    { type: "building", start: 28.5, end: 30 },
                    { type: "curing", start: 30, end: 31.5 },
                    { type: "buffer", start: 31.5, end: 32 },
                ],
            },
        ],
    },

    {
        id: "line-2",
        machine: "MC 2",
        shift: "All Shifts",
        rows: [
            // Shift 1
            {
                code: "4345",
                balanceOut: 100,
                qty: 350,
                stock: 80,
                totalQty: 1000,
                startTime: "08:00",
                endTime: "16:00",
                start: 8,
                end: 16,
                remark: "Shift 1",
                rim: "16",
                cureShift: 42,
                rcStock: 12,
                cureEst: "08:10",
                buildTime: "08:00 - 11:00",
                shiftNum: 1,
                phases: [
                    { type: "building", start: 8, end: 11 },
                    { type: "curing", start: 11, end: 15 },
                    { type: "idle", start: 15, end: 16 },
                ],
            },
            // Shift 2 - Multi Code
            {
                code: "4667",
                balanceOut: 100,
                qty: 300,
                stock: 90,
                totalQty: 1200,
                startTime: "16:00",
                endTime: "20:00",
                start: 16,
                end: 20,
                remark: "Shift 2",
                rim: "18",
                cureShift: 25,
                rcStock: 30,
                cureEst: "16:10",
                buildTime: "16:30 - 18:00",
                shiftNum: 2,
                phases: [
                    { type: "building", start: 16.5, end: 18 },
                    { type: "curing", start: 18, end: 19.5 },
                    { type: "idle", start: 19.5, end: 20 },
                ],
            },
            {
                code: "4617",
                balanceOut: 100,
                qty: 450,
                stock: 300,
                totalQty: 1500,
                startTime: "20:00",
                endTime: "24:00",
                start: 20,
                end: 24,
                remark: "Shift 2",
                rim: "17",
                cureShift: 23,
                rcStock: 25,
                cureEst: "20:15",
                buildTime: "20:30 - 22:30",
                shiftNum: 2,
                phases: [
                    { type: "building", start: 20.5, end: 22.5 },
                    { type: "curing", start: 22.5, end: 24 },
                ],
            },
            // Shift 3
            {
                code: "4617",
                balanceOut: 100,
                qty: 400,
                stock: 150,
                totalQty: 1000,
                startTime: "00:00",
                endTime: "08:00",
                start: 24,
                end: 32,
                remark: "Shift 3",
                rim: "17",
                cureShift: 35,
                rcStock: 10,
                cureEst: "00:05",
                buildTime: "01:30 - 04:00",
                shiftNum: 3,
                phases: [
                    { type: "idle", start: 24, end: 25.5 },
                    { type: "curing", start: 25.5, end: 30.5 },
                    { type: "buffer", start: 30.5, end: 32 },
                ],
            },
        ],
    },

    {
        id: "line-3",
        machine: "MC 3",
        shift: "All Shifts",
        rows: [
            {
                code: "4392",
                balanceOut: 100,
                qty: 250,
                stock: 40,
                totalQty: 800,
                startTime: "08:00",
                endTime: "13:00",
                start: 8,
                end: 13,
                remark: "Shift 1",
                rim: "14",
                cureShift: 20,
                rcStock: 10,
                cureEst: "08:10",
                buildTime: "08:30 - 11:00",
                shiftNum: 1,
                phases: [
                    { type: "building", start: 8.5, end: 11 },
                    { type: "curing", start: 11, end: 13 },
                ],
            },
            {
                code: "4617",
                balanceOut: 100,
                qty: 500,
                stock: 40,
                totalQty: 800,
                startTime: "13:00",
                endTime: "21:00",
                start: 13,
                end: 21,
                remark: "Shift 1/2",
                rim: "17",
                cureShift: 39,
                rcStock: 15,
                cureEst: "13:20",
                buildTime: "13:30 - 16:00",
                shiftNum: 2,
                phases: [
                    { type: "building", start: 13.5, end: 16 },
                    { type: "curing", start: 16, end: 20 },
                    { type: "idle", start: 20, end: 21 },
                ],
            },
            {
                code: "4392",
                balanceOut: 100,
                qty: 750,
                stock: 40,
                totalQty: 800,
                startTime: "21:00",
                endTime: "08:00",
                start: 21,
                end: 32,
                remark: "Shift 2/3",
                rim: "14",
                cureShift: 60,
                rcStock: 10,
                cureEst: "21:30",
                buildTime: "22:00 - 02:00",
                shiftNum: 3,
                phases: [
                    { type: "building", start: 22, end: 26 },
                    { type: "curing", start: 26, end: 31 },
                    { type: "buffer", start: 31, end: 32 },
                ],
            },
        ],
    },

    {
        id: "line-4",
        machine: "MC 4",
        shift: "All Shifts",
        rows: [
            {
                code: "4667",
                balanceOut: 100,
                qty: 750,
                stock: 90,
                totalQty: 1200,
                startTime: "08:00",
                endTime: "16:00",
                start: 8,
                end: 16,
                remark: "Shift 1",
                rim: "18",
                cureShift: 50,
                rcStock: 30,
                cureEst: "08:00",
                buildTime: "08:00 - 11:00",
                shiftNum: 1,
                phases: [
                    { type: "building", start: 8, end: 11 },
                    { type: "curing", start: 11, end: 14 },
                    { type: "idle", start: 14, end: 15 },
                    { type: "buffer", start: 15, end: 16 },
                ],
            },
            {
                code: "4345",
                balanceOut: 100,
                qty: 750,
                stock: 90,
                totalQty: 1200,
                startTime: "16:00",
                endTime: "24:00",
                start: 16,
                end: 24,
                remark: "Shift 2",
                rim: "16",
                cureShift: 50,
                rcStock: 15,
                cureEst: "16:20",
                buildTime: "16:30 - 19:30",
                shiftNum: 2,
                phases: [
                    { type: "building", start: 16.5, end: 19.5 },
                    { type: "curing", start: 19.5, end: 23 },
                    { type: "buffer", start: 23, end: 24 },
                ],
            },
            {
                code: "4667",
                balanceOut: 100,
                qty: 750,
                stock: 90,
                totalQty: 1200,
                startTime: "00:00",
                endTime: "08:00",
                start: 24,
                end: 32,
                remark: "Shift 3",
                rim: "18",
                cureShift: 50,
                rcStock: 30,
                cureEst: "00:15",
                buildTime: "00:00 - 03:00",
                shiftNum: 3,
                phases: [
                    { type: "building", start: 24, end: 27 },
                    { type: "curing", start: 27, end: 31 },
                    { type: "idle", start: 31, end: 32 },
                ],
            },
        ],
    },

    {
        id: "line-5",
        machine: "MC 5",
        shift: "All Shifts",
        rows: [
            {
                code: "4528",
                balanceOut: 100,
                qty: 750,
                stock: 0,
                totalQty: 750,
                startTime: "08:00",
                endTime: "16:00",
                start: 8,
                end: 16,
                remark: "Shift 1",
                rim: "14",
                cureShift: 39,
                rcStock: 5,
                cureEst: "08:20",
                buildTime: "08:30 - 10:30",
                shiftNum: 1,
                phases: [
                    { type: "building", start: 8.5, end: 10.5 },
                    { type: "curing", start: 10.5, end: 14 },
                    { type: "idle", start: 14, end: 15 },
                    { type: "buffer", start: 15, end: 16 },
                ],
            },
            {
                code: "4528",
                balanceOut: 100,
                qty: 750,
                stock: 0,
                totalQty: 750,
                startTime: "16:00",
                endTime: "24:00",
                start: 16,
                end: 24,
                remark: "Shift 2",
                rim: "14",
                cureShift: 39,
                rcStock: 5,
                cureEst: "16:30",
                buildTime: "17:00 - 20:00",
                shiftNum: 2,
                phases: [
                    { type: "building", start: 17, end: 20 },
                    { type: "curing", start: 20, end: 23 },
                    { type: "buffer", start: 23, end: 24 },
                ],
            },
            {
                code: "4528",
                balanceOut: 100,
                qty: 750,
                stock: 0,
                totalQty: 750,
                startTime: "00:00",
                endTime: "08:00",
                start: 24,
                end: 32,
                remark: "Shift 3",
                rim: "14",
                cureShift: 39,
                rcStock: 5,
                cureEst: "01:00",
                buildTime: "01:00 - 04:00",
                shiftNum: 3,
                phases: [
                    { type: "building", start: 25, end: 28 },
                    { type: "curing", start: 28, end: 31 },
                    { type: "idle", start: 31, end: 32 },
                ],
            },
        ],
    },
];

export const scheduleBlocksLine2 = [
    {
        id: "line-2-mc-11",
        machine: "MC 11",
        shift: "All Shifts",
        rows: [
            {
                code: "4617",
                balanceOut: 100,
                qty: 200,
                stock: 250,
                totalQty: 1000,
                startTime: "08:00",
                endTime: "11:00",
                start: 8,
                end: 11,
                remark: "Shift 1",
                rim: "17",
                cureShift: 15,
                rcStock: 5,
                cureEst: "08:30",
                buildTime: "08:30 - 10:00",
                shiftNum: 1,
                phases: [
                    { type: "building", start: 8.5, end: 10 },
                    { type: "curing", start: 10, end: 11 },
                ],
            },
            {
                code: "4345",
                balanceOut: 100,
                qty: 400,
                stock: 250,
                totalQty: 1000,
                startTime: "11:00",
                endTime: "16:00",
                start: 11,
                end: 16,
                remark: "Shift 1",
                rim: "16",
                cureShift: 30,
                rcStock: 10,
                cureEst: "11:20",
                buildTime: "11:30 - 14:00",
                shiftNum: 1,
                phases: [
                    { type: "building", start: 11.5, end: 14 },
                    { type: "curing", start: 14, end: 15.5 },
                    { type: "idle", start: 15.5, end: 16 },
                ],
            },
            {
                code: "4617",
                balanceOut: 100,
                qty: 600,
                stock: 250,
                totalQty: 1000,
                startTime: "16:00",
                endTime: "24:00",
                start: 16,
                end: 24,
                remark: "Shift 2",
                rim: "17",
                cureShift: 45,
                rcStock: 15,
                cureEst: "16:40",
                buildTime: "17:00 - 20:00",
                shiftNum: 2,
                phases: [
                    { type: "building", start: 17, end: 20 },
                    { type: "curing", start: 20, end: 23 },
                    { type: "buffer", start: 23, end: 24 },
                ],
            },
            {
                code: "4617",
                balanceOut: 100,
                qty: 600,
                stock: 250,
                totalQty: 1000,
                startTime: "00:00",
                endTime: "08:00",
                start: 24,
                end: 32,
                remark: "Shift 3",
                rim: "17",
                cureShift: 45,
                rcStock: 15,
                cureEst: "01:00",
                buildTime: "01:00 - 04:00",
                shiftNum: 3,
                phases: [
                    { type: "building", start: 25, end: 28 },
                    { type: "curing", start: 28, end: 31 },
                    { type: "idle", start: 31, end: 32 },
                ],
            },
        ],
    },
    {
        id: "line-2-mc-12",
        machine: "MC 12",
        shift: "All Shifts",
        rows: [
            {
                code: "4742",
                balanceOut: 100,
                qty: 500,
                stock: 100,
                totalQty: 800,
                startTime: "08:00",
                endTime: "16:00",
                start: 8,
                end: 16,
                remark: "Shift 1",
                rim: "18",
                cureShift: 42,
                rcStock: 12,
                cureEst: "08:15",
                buildTime: "08:00 - 11:00",
                shiftNum: 1,
                phases: [
                    { type: "building", start: 8, end: 11 },
                    { type: "curing", start: 11, end: 15 },
                    { type: "buffer", start: 15, end: 16 },
                ],
            },
            {
                code: "4742",
                balanceOut: 100,
                qty: 250,
                stock: 100,
                totalQty: 800,
                startTime: "16:00",
                endTime: "20:00",
                start: 16,
                end: 20,
                remark: "Shift 2",
                rim: "18",
                cureShift: 21,
                rcStock: 6,
                cureEst: "16:50",
                buildTime: "17:00 - 18:30",
                shiftNum: 2,
                phases: [
                    { type: "building", start: 17, end: 18.5 },
                    { type: "curing", start: 18.5, end: 20 },
                ],
            },
            {
                code: "4346",
                balanceOut: 100,
                qty: 250,
                stock: 100,
                totalQty: 800,
                startTime: "20:00",
                endTime: "24:00",
                start: 20,
                end: 24,
                remark: "Shift 2",
                rim: "16",
                cureShift: 21,
                rcStock: 6,
                cureEst: "20:30",
                buildTime: "21:00 - 22:30",
                shiftNum: 2,
                phases: [
                    { type: "building", start: 21, end: 22.5 },
                    { type: "curing", start: 22.5, end: 24 },
                ],
            },
            {
                code: "4742",
                balanceOut: 100,
                qty: 500,
                stock: 100,
                totalQty: 800,
                startTime: "00:00",
                endTime: "08:00",
                start: 24,
                end: 32,
                remark: "Shift 3",
                rim: "18",
                cureShift: 42,
                rcStock: 12,
                cureEst: "00:45",
                buildTime: "01:00 - 04:00",
                shiftNum: 3,
                phases: [
                    { type: "building", start: 25, end: 28 },
                    { type: "curing", start: 28, end: 31 },
                    { type: "idle", start: 31, end: 32 },
                ],
            },
        ],
    },
];

export const PRODUCTION_LINES = [
    { id: "pcr-1", name: "PCR Line 1", data: scheduleBlocksLine1 },
    { id: "pcr-2", name: "PCR Line 2", data: scheduleBlocksLine2 },
];
